
services:
  frontend:
    build: .
    container_name: frontend-container
    ports:
      - "8080:80"  # Frontend vil være tilgængelig på http://localhost:8080
    depends_on:
      - backend  # Sørg for, at backend er oppe, før frontend startes
    networks:
      - app-network  # Forbind frontend til netværket, så det kan kommunikere med backend

  backend:
    build: .  # Bygger backend fra den aktuelle mappe
    container_name: backend-container
    ports:
      - "3000:3000"  # Backend vil være tilgængelig på http://localhost:3000
    environment:
      - MONGO_URI=mongodb://mongodb:27017/bilDB  # MongoDB URI
    depends_on:
      - mongodb  # Sørg for, at MongoDB er oppe, før backend startes
    networks:
      - app-network  # Forbind backend til netværket

  mongodb:
    image: mongo  # Bruger MongoDB image
    container_name: mongodb  # Sætter container-navnet til mongodb
    ports:
      - "27017:27017"  # MongoDB vil være tilgængelig på http://localhost:27017
    volumes:
      - mongodb-data:/data/db  # Persistent storage for MongoDB data
    networks:
      - app-network  # Forbind MongoDB til netværket

networks:
  app-network:  # Opretter et netværk, så containere kan kommunikere med hinanden

volumes:
  mongodb-data:  # Persistent storage for MongoDB data
