
services:
  backend:
    build: .
    container_name: backend-container
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/bilDB
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network

networks:
  app-network:

volumes:
  mongodb-data:
